resources:
# Source Code
- name: spring-petclinic
  type: git
  source:
    uri: https://github.com/techgnosis/spring-petclinic.git
    branch: demo
- name: tanzu-gitops
  type: git
  source:
    uri: git@github.com:techgnosis/tanzu-gitops.git
    branch: master
    paths:
      - manifests/spring-petclinic/*
    private_key: |
      ((tanzu-gitops.concourse_github_privatekey))

# Tasks
- name: concourse
  type: git
  source:
    uri: https://github.com/techgnosis/concourse.git
    branch: master
# Images
- name: adoptopenjdk
  type: registry-image
  source:
    repository: adoptopenjdk
    tag: 14.0.2_8-jdk-hotspot
- name: spring-petclinic-image
  type: docker-image
  source:
    repository: harbor.lab.home/library/spring-petclinic
    ca_certs:
    - domain: harbor.lab.home
      cert: |
        ((tanzu-gitops.ca_cert))
- name: concourse-helper
  type: docker-image
  source:
    repository: harbor.lab.home/library/concourse-helper
    tag: latest
    ca_certs:
    - domain: harbor.lab.home
      cert: |
        ((tanzu-gitops.ca_cert))

  


jobs:
- name: spring-petclinic-test-and-build-with-TBS
  public: true
  serial: true
  plan:
  - get: spring-petclinic
    trigger: true
  - get: adoptopenjdk
  - get: concourse-helper
  - get: concourse
  - task: maven-test
    file: concourse/tasks/maven-test/maven-test.yml
    image: adoptopenjdk
    input_mapping:
      app-source: spring-petclinic
  - task: maven-checkstyle
    image: adoptopenjdk
    file: concourse/tasks/maven-checkstyle/maven-checkstyle.yml
    input_mapping:
      app-source: spring-petclinic
  - task: tbs-build
    image: concourse-helper
    file: concourse/tasks/tbs-build/tbs-build.yml
    input_mapping:
      app-source: spring-petclinic
    params:
      tkgicluster: ((tanzu-gitops.tkgicluster))
      tkgiapi: ((tanzu-gitops.tkgiapi))
      tkgiuser: ((tanzu-gitops.tkgiuser))
      tkgipassword: ((tanzu-gitops.tkgipassword))
      namespace: spring-petclinic
      imagename: spring-petclinic


- name: spring-petclinic-deploy-new-image
  public: true
  serial: true
  plan:
    - get: spring-petclinic-image
      trigger: true
    - get: tanzu-gitops
    - get: concourse
    - get: concourse-helper
    - task: deploy image
      file: concourse/tasks/deploy-image/deploy-image.yml
      image: concourse-helper
      input_mapping:
        deploy-source: tanzu-gitops
        image: spring-petclinic-image
      params:
        tkgicluster: ((tanzu-gitops.tkgicluster))
        tkgiapi: ((tanzu-gitops.tkgiapi))
        tkgiuser: ((tanzu-gitops.tkgiuser))
        tkgipassword: ((tanzu-gitops.tkgipassword))
        imagename: spring-petclinic
    - put: tanzu-gitops
      params: {repository: deploy-source-modified}

- name: deploy
  public: true
  serial: true
  plan:
    - get: tanzu-gitops
      trigger: true
    - get: concourse-helper
    - get: concourse
    - task: kapp deploy
      image: concourse-helper
      file: concourse/tasks/kapp-deploy/kapp-deploy.yml
      input_mapping:
        deploy-source: tanzu-gitops
      params:
        tkgicluster: ((tanzu-gitops.tkgicluster))
        tkgiapi: ((tanzu-gitops.tkgiapi))
        tkgiuser: ((tanzu-gitops.tkgiuser))
        tkgipassword: ((tanzu-gitops.tkgipassword))
        appname: spring-petclinic
    - task: create wavefront event
      image: concourse-helper
      file: concourse/tasks/wavefront-event/wavefront-event.yml

