---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: harbor.lab.home/library/petclinic@sha256:6cade02d3720886cefd381761b7ebb900f406c63ef36391fd8e7abefccb581da
        ports:
        - containerPort: 8080
