apiVersion: v1
kind: Namespace
metadata:
  name: concourse
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: concourse
  namespace: concourse
spec:
  helmVersion: v3
  targetNamespace: concourse
  releaseName: concourse
  wait: true
  test:
    enable: true
  chart:
    repository: https://concourse-charts.storage.googleapis.com/
    name: concourse
    version: "11.4.0"
  values:
    concourse:
      web:
        externalUrl: https://concourse.lab.home
    web:
      ingress:
        enabled: true
        hosts:
          - concourse.lab.home
        tls:
          - secretName: concourse-web-tls
            hosts:
              - concourse.lab.home