---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: harbor.lab.home/library/spring-petclinic@sha256:ca3dcf1f857bff2537d7bf68a18e95fa54fcaeb0cd2d981e84cf6ff5c6f871be
        ports:
        - containerPort: 8080
        env:
        - name: WAVEFRONT_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: wavefront
              key: wavefront_api_token
        - name: WAVEFRONT_URL
          valueFrom:
            secretKeyRef:
              name: wavefront
              key: wavefront_url
