---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: harbor.lab.home/library/spring-petclinic@sha256:7be1aa9dcbdcceff3b862947c71ec2dab92f5cd14627cddba591128be2ec8e7c
        ports:
        - containerPort: 8080
        env:
        - name: WAVEFRONT_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: wavefront
              key: wavefront_api_token
        - name: WAVEFRONT_URL
          valueFrom:
            secretKeyRef:
              name: wavefront
              key: wavefront_url
        - name: spring_profiles_active
          value: mysql
